### ISSUE TITLE
null_cond_prob 

### ISSUE THREAD

**Issue by h-bouzid** [nihaomiao/CVPR2023_LFDM#46]
Hi dear @nihaomiao, 
Could you please explain to me what is the role of null_cond_prob variable? I couldnt fully grasp it.

and why do you change it from training 0.1 to test 1? 

Thank  you for your time

**Comment by nihaomiao** [comment]
Hi, @h-bouzid, thanks for your interest in our paper! During training, we use classifier-free guidance, which needs to switch between unconditional and conditional generation modes. This is controlled by ``null_cond_prob``. During testing, as shown in Table 6, using guidance can slightly improve the FVD score but double the inference time (since we need to run both unconditional and conditional generation at each reverse step). So we choose 1 as the default setting.
